### ISSUE TITLE
SyntaxError: Unexpected token ' in JSON at position 1

### ISSUE THREAD

**Issue by karneaud** [CDNievas/heroku-action#1]
Running your action and encountered the subject error

> Buildpacks cleared. Next release on fac-lumen-api will detect buildpacks normally.
> heroku: Press any key to open up the browser to login or q to exit: undefined:1
> ['https://github.com/heroku/heroku-buildpack-php.git']
>  ^
> 
> SyntaxError: Unexpected token ' in JSON at position 1
>     at JSON.parse (<anonymous>)
>     at addBuildpacks (/home/runner/work/_actions/CDNievas/heroku-action/v1.0/index.js:40:27)

My yml

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "fxxxxxxxx"
          useforce: true
          branch: "release/staging"
          dynamicFiles: true
          procfile: "web: vendor/bin/heroku-php-apache2 public/"
          buildpacks: "['https://github.com/heroku/heroku-buildpack-php.git']"
```
