### ISSUE TITLE
Press any key to open up the browser to login or q to exit: child_process.js:660     throw err;

### ISSUE THREAD

**Issue by Klaudeta** [CDNievas/heroku-action#3]
Running your action I get this exception:

```
Added git remote heroku
Buildpacks cleared. Next release on klau-package-viewer-backend will detect buildpacks normally.
Buildpack set. Next release on klau-package-viewer-backend will use heroku-community/multi-procfile.
Run git push heroku main to create a new release using this buildpack.
Buildpack added. Next release on klau-package-viewer-backend will use:
  1. heroku-community/multi-procfile
  2. heroku/nodejs
Run git push heroku main to create a new release using these buildpacks.
Added buildpacks
HEAD detached from a7fdcf0
nothing to commit, working tree clean
heroku: Press any key to open up the browser to login or q to exit: child_process.js:660
    throw err;
    ^

Error: Command failed: git add -A . && git commit -m "Added dynamic files"
    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at execComm (/home/runner/work/_actions/CDNievas/heroku-action/v1.0/index.js:1[45](https://github.com/Klaudeta/view-packages-pro/runs/5338899550?check_suite_focus=true#step:3:45):10)
    at addDynamicFiles (/home/runner/work/_actions/CDNievas/heroku-action/v1.0/index.js:59:5)
    at Object.<anonymous> (/home/runner/work/_actions/CDNievas/heroku-action/v1.0/index.js:15:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:10[47](https://github.com/Klaudeta/view-packages-pro/runs/5338899550?check_suite_focus=true#step:3:47):10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 1705,
  stdout: null,
  stderr: null
```

and my config is as follow:

```
name: Push stack to heroku
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release backend
        uses: CDNievas/heroku-action@v1.0
        with:
          heroku_api_key: ${{secrets.HEROKU_SECRET}}
          heroku_app_name: klau-package-viewer-backend
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          useforce: true,
          buildpacks: "[\"heroku-community/multi-procfile\", \"heroku/nodejs\"]"
          procfile: "web: yarn workspace backend start"
          appdir: "apps/backend"
............
```
